version: "3.7"

services:
  app:
    image: eqtest
    ports:
      - 8080:8080
  environment:
      MYSQL_HOST: "mysql"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "test"
      MYSQL_DB: "test"

mysql:
  image: "mysql:8.0.13"
  volumes:
    - ./test-mysql-data:/var/lib/mysql
  environment:
      MYSQL_ROOT_PASSWORD: "test" 
      MYSQL_DATABASE: "test"